# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

controller_manager:
  ros__parameters:
    update_rate: 1000

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: [fl_wheel_joint, rl_wheel_joint]
    right_wheel_names: [fr_wheel_joint, rr_wheel_joint]

    wheel_separation: 0.697
    wheel_radius: 0.1825

    use_stamped_vel: false

joint_trajectory_controller:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
